version: '3.8'

services:
  postgres_geospatial:
    image: postgis/postgis
    environment:
      POSTGRES_DB: geospatial_db
      POSTGRES_USER: acqua
      POSTGRES_PASSWORD: acqua
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      # - ./bin/mydb.dump:/docker-entrypoint-initdb.d/mybd.dump

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: acqua@example.com
      PGADMIN_DEFAULT_PASSWORD: acqua
    ports:
      - "5050:80"

  postgres_poc:
    image: postgres:latest
    container_name: postgres_exemplo
    environment:
      POSTGRES_USER: acqua
      POSTGRES_PASSWORD: acqua
      POSTGRES_DB: monitora
    ports:
      - "5433:5432"
    volumes:
      - ./scripts/:/docker-entrypoint-initdb.d

  backend:
    build:
      dockerfile: ./docker/app.dockerfile
      context: .
    container_name: backend
    volumes:
      - ./:/src/app
    ports:
      - "3333:3333"
    depends_on:
      - postgres_poc
    tty: true

volumes:
  pg_data: